spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.6.15:3306/fangchankanjia?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: laike
    password: laike123
  jackson:
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  #  resources:
  #    chain:
  #      cache: false
  #    static-locations: D:/project/kuaidi/src/main/resources/
  #  mvc:
  #    static-path-pattern: /static/**
  #    servlet:
  #      load-on-startup: 1

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制） max-active: 2000
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
  data:
    couchbase:
      type-key:
  flyway:
    license-key:

server:
  port: 8083

mybatis-plus:
  type-aliases-package: com.laike.kuaidi.*.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
      id-type: auto
user:
  appId: wx17b408c51869158a
  appSecret: c9717e4eebfd8d2c3c2df54568797b38
  orderName: 天府之国

